# https://www.learnopencv.com/install-opencv3-on-ubuntu/

FROM nvidia/cuda:10.1-devel-ubuntu18.04
LABEL maintainer "usmanmaqbool@outlook.com"
ENV OPENCV_VERSION 3.4.2

#RUN add-apt-repository -y ppa:deadsnakes/ppa
# Install all dependencies for OpenCV
RUN apt-get -y update && \
    apt-get -y install \
        python3 \
        python3-dev \
        git \
        wget \
        unzip \
        cmake \
        build-essential \
        pkg-config \
        software-properties-common \
        gfortran \
        libgtk2.0-dev \
        libavcodec-dev \
        libavformat-dev \
        libswscale-dev \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libv4l-dev \
        python3.8 \
    && \

# install python dependencies
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    pip3 install numpy \


# Install OpenCV

# Define default command.
# CMD ["python3", "--version"]
